name: Deploy to Algorithmia

on:
  push:
    branches:
      - main
    paths-ignore:
      - ‘**/README.md’
      - ‘**/model_manifest.json’

jobs:
  algorithmia-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Main Repo
        uses: actions/checkout@v2.0.0
        with:
          ref: ${{github.sha}}
      - name: Deploy Model to Algorithmia
        uses: algorithmiaio/algorithmia-modeldeployment-action@1.1.0
        env:
          HEAD_COMMIT_MSG: ${{ github.event.head_commit.message }}
        with:
          algorithmia_api: ${{ secrets.ALGORITHMIA_API }}
          algorithmia_api_key: ${{ secrets.ALGORITHMIA_API_KEY }}
          algorithmia_username: ${{ secrets.ALGORITHMIA_USERNAME }}
          algorithmia_email: ${{ secrets.ALGORITHMIA_EMAIL }}
          algorithmia_algoname:  sentiment_analysis_gha
          algorithmia_password: ${{ secrets.ALGORITHMIA_PASSWORD }}
          git_host: git.algosales.productionize.ai
        
